# Uncomment this line to define a global platform for your project

platform :ios, ’9.0'
# Uncomment this line if you're using Swift
# use_frameworks!


# インストールするpodをまとめた定数
def install_pods
    ##pod 'SFHFKeychainUtils'
    ##pod 'UIDevice-Hardware'
    pod 'SVProgressHUD'
    pod 'MBProgressHUD'
end


# PayNoteBeta 開発版(com.azukid.b3c6bd451bb03c) 常に先行公開
target 'PayNoteBeta' do
    install_pods
end

# PayNote 安定版(com.azukid.AzCreditS1)
target 'PayNote' do
	install_pods
end


#OLD
target 'PayNoteFree' do
    install_pods
end
target 'PayNoteS1Pad' do
    install_pods
end
target 'PayNotePadFree' do
    install_pods
end


